version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logs_parser_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:1.25
    container_name: logs_parser_nginx
    ports:
      - "8088:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:10.11
    container_name: logs_parser_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
